version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id

        # freshness test:
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day

        columns:
          - name: date_date
            description: date de commande
          - name: orders_id
            description: id unique de la commande
          - name: products_id
            description: id du produit commandé
          - name: revenue
            description: chiffre d'affaire
          - name: quantity
            description: quantité commandée
      - name: product
        identifier: raw_gz_product
        description: product of Greenweez / une ligne par produit avec les purchase_price
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique:
                  column_name: products_id
              - not_null:
                  column_name: products_id
          - name: purchase_price
            description: prix d'achat
      - name: ship
        identifier: raw_gz_ship
        description: shipping of greenweez / une ligne par commande avec les couts logistique set de livraison
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique:
                  column_name: orders_id
              - not_null:
                  column_name: orders_id
          - name: shipping_fee
            description: frais d'expédition - payé par le client
          - name: logcost
            description: cout logistique
          - name: ship_cost
            description: cout d'expedition - payé par l'entreprise
