version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date de commande
          - name: orders_id
            description: id unique de la commande
          - name: products_id
            description: id du produit commandé
          - name: revenue
            description: chiffre d'affaire
          - name: quantity
            description: quantité commandée
      - name: product
        identifier: raw_gz_product
        description: product of Greenweez / une ligne par produit avec les purchase_price
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique:
                  column_name: products_id
              - not_null:
                  column_name: products_id
          - name: purchase_price
            description: prix d'achat
      - name: ship
        identifier: raw_gz_ship
        description: shipping of greenweez / une ligne par commande avec les couts logistique set de livraison
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique:
                  column_name: orders_id
              - not_null:
                  column_name: orders_id
          - name: shipping_fee
            description: frais d'expédition - payé par le client
          - name: logcost
            description: cout logistique
          - name: ship_cost
            description: cout d'expedition - payé par l'entreprise
      - name : adwords
        identifier: raw_gz_adwords
        description: table pour adwords
        columns:
          - name: date_date
            description: date 
          - name: paid_source
            description: qui a payé
          - name: campaign_key
            description: référence de la campagne
          - name: camPGN_name
            description: ??
          - name: ads_cost
            description: couts de la pub
          - name: impression
            description: nombre de vue
          - name: click
            description: nombre de clics             
      - name : bing
        identifier: raw_gz_bing
        description: table pour bing
        columns:
          - name: date_date
            description: date 
          - name: paid_source
            description: qui a payé
          - name: campaign_key
            description: référence de la campagne
          - name: camPGN_name
            description: ??
          - name: ads_cost
            description: couts de la pub
          - name: impression
            description: nombre de vue
          - name: click
            description: nombre de clics
      - name : criteo
        identifier: raw_gz_criteo
        description: table pour criteo
        columns:
          - name: date_date
            description: date 
          - name: paid_source
            description: qui a payé
          - name: campaign_key
            description: référence de la campagne
          - name: camPGN_name
            description: ??
          - name: ads_cost
            description: couts de la pub
          - name: impression
            description: nombre de vue
          - name: click
            description: nombre de clics
      - name : facebook
        identifier: raw_gz_facebook
        description: table pour facebook
        columns:
          - name: date_date
            description: date 
          - name: paid_source
            description: qui a payé
          - name: campaign_key
            description: référence de la campagne
          - name: camPGN_name
            description: ??
          - name: ads_cost
            description: couts de la pub
          - name: impression
            description: nombre de vue
          - name: click
            description: nombre de clics

models:
   - name: int_orders_margin
     description: calcul de la marge par commande
     columns:
       - name: orders_id
         description: primary key
         tests:
           - unique:
               column_name : orders_id

   - name: int_campaigns
     description: add campaigns
     columns:
      - name : date_date
        description: date 
      - name: paid_source
        description: qui a payé
      - name: campaign_key
        description: référence de la campagne
      - name: camPGN_name
        description: ??
      - name: ads_cost
        description: couts de la pub
      - name: impression
        description: nombre de vue
      - name: click
        description: nombre de clics